require "prism"

require_relative "active_mutator/version"

module ActiveMutator
  Error = Class.new(StandardError)
  BaselineFailed = Class.new(Error)
end

require_relative "active_mutator/edit"
require_relative "active_mutator/splicer"
require_relative "active_mutator/subject"
require_relative "active_mutator/subject_finder"
require_relative "active_mutator/subject_matcher"
require_relative "active_mutator/operators/base"
require_relative "active_mutator/operators/conditional_boundary"
require_relative "active_mutator/operators/condition_forcing"
require_relative "active_mutator/operators/logical_operator"
require_relative "active_mutator/operators/literal"
require_relative "active_mutator/operators/statement_deletion"
require_relative "active_mutator/operators/early_return"
require_relative "active_mutator/operators/call_swap"
require_relative "active_mutator/operators/negation_removal"
require_relative "active_mutator/mutation"
require_relative "active_mutator/analysis"
require_relative "active_mutator/engine"
require_relative "active_mutator/atomic_file"
require_relative "active_mutator/coverage_map"
require_relative "active_mutator/baseline"
require_relative "active_mutator/baseline_delta"
require_relative "active_mutator/inserter"
require_relative "active_mutator/worker"
require_relative "active_mutator/result"
require_relative "active_mutator/work_item"
require_relative "active_mutator/scheduler"
require_relative "active_mutator/reporter/operator_stats"
require_relative "active_mutator/reporter/terminal"
require_relative "active_mutator/reporter/github"
require_relative "active_mutator/reporter/json"
require_relative "active_mutator/source_location"
require_relative "active_mutator/since_filter"
require_relative "active_mutator/fingerprint"
require_relative "active_mutator/accepted_ledger"
require_relative "active_mutator/reporter/stryker_json"
require_relative "active_mutator/config"
require_relative "active_mutator/runner"
require_relative "active_mutator/config_file"
require_relative "active_mutator/cli"
